#!/bin/bash

# walltime (hh:mm::ss)
#PBS -l walltime=00:01:00

#PBS -l nodes=1:ppn=6
#PBS -l pmem=1gb
#PBS -u anioche

#PBS -o /home/anioche/logs/${PBS_JOBNAME}.out
#PBS -e /home/anioche/logs/${PBS_JOBNAME}.err

#PBS -m abe
#PBS -M clusterresultssimulation@gmail.com

cd $PBS_O_WORKDIR

# replace "3.6.4" by your pyenv's virtual environment name.
# if you do not have pyenv, python version will be unchanged.
export PYENV_VERSION=3.6.4

python main.py ${PBS_ARRAYID}

unset PYENV_VERSION
